export { default as Home } from './Home'
export { default as About } from './About'
export { default as Products } from './Products'
export { default as Contacts } from './Contacts'
export { default as Price } from './Price'
export { default as Gallery } from './Gallery'